### ISSUE TITLE
Utterance ID for L1 language scripts

### ISSUE THREAD

**Issue by shangeth** [iiscleap/NISP-Dataset#1]
Eg:
Hindi_master/scripts/Hindi_txt/uniq/Hin_0001_Hin_f.txt file has the Hindi scripts for speaker ID:0001, but how to match the sentence with the wav files in NISP-Dataset/Hindi_master/Hindi/?
```



 इसके कारण उपभोक्ताआें को सीधा फायदा होगा। 






 सहारा मरुस्थल से जुड़ी रिसर्च का नेतृत्व करने वाले एमआईटी के पूर्व अनुसंधानकर्ता
 चार्लोट ने पिछले दो   लाख चालीस  हजार साल तक जमा हुईं पर्तों का विश्लेषण
 किया है। 




 यह भी बताए कि वापस लिए गए केस दोबारा शुरू करने के लिए कोई कानून है या
 नहीं। 



```

and what is the purpose of empty lines in the file?

**Comment by shareefbabu** [comment]
Hi,

Each wav file is considered with one line,  (to one full stop | )

There are seven empty lines in that between each sentence.. That was a
trick we applied to make each sentence as one image.
Hindi_master/scripts/Hindi_txt/uniq/Hin_0001_Hin_f.txt  ==> this is a link
to UTF8 transcripts
 Hindi_images_xml will direct to each utterance corresponding to each wav
file. (hindi_images_xml )
<https://github.com/iiscleap/NISP-Dataset/tree/master/Hindi_master/scripts/Hindi_txt/hindi_images_xml>


The sequence of the recorded files is as follows
1. first two sentences are common sentences.
2. next in sequence uinq sentences
3. next in sequence para sentences

If any mismatch in the number of utterances  ( there would mostly in uniq
sentences -- image files would be more than the recorded ) this piece of
annotation we missed while uploading the data..

We will take up shortly to fix the mismatch in the number of
images(sentences) Vs recorded sentences

Thanks
Shareef
