### ISSUE TITLE
Unable to extract data

### ISSUE THREAD

**Issue by akashicMarga** [iiscleap/NISP-Dataset#2]
Hi, thanks for the dataset!!
how can we extract the dataset?
I am getting the below error while extracting tar files in NISP-Dataset/Hindi_master/Hindi

Steps for extraction:
1. cat RECS.tar.gz* > temp.tar.gz
2. tar zxvf temp.tar.gz

tar: This does not look like a tar archive
tar: Skipping to next header
tar: Archive contains ‘4\037\332h\026\374g\r\274j\030Z’ where numeric off_t value expected
tar: Archive contains ‘F=\247.P;\250\371U5t+’ where numeric off_t value expected
tar: Exiting with failure status due to previous errors

**Comment by shareefbabu** [comment]
extract all the tar files together,

Individual tar files could be throwing that error.

Please download all the data then untar it ..

Best!!

**Comment by skuma17** [comment]
Hi, 

  Can you give clear instruction on how to untar this datasets after downloading ?

-satish
